app/controllers/ClaimOnlineController.scala, app/controllers/MoreThanFiveJobsController.scala, app/controllers/RegisterForSelfAssessmentController.scala, app/controllers/UsePrintAndPostController.scala, app/forms/MoreThanFiveJobsFormProvider.scala, app/identifiers/MoreThanFiveJobsId.scala, app/models/Claimant.scala, app/utils/Navigator.scala, app/views/claimOnline.scala.html, app/views/moreThanFiveJobs.scala.html, app/views/registerForSelfAssessment.scala.html, app/views/usePrintAndPost.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/ClaimOnline.sh, migrations/applied_migrations/MoreThanFiveJobs.sh, migrations/applied_migrations/RegisterForSelfAssessment.sh, migrations/applied_migrations/UsePrintAndPost.sh, test/controllers/ClaimOnlineControllerSpec.scala, test/controllers/MoreThanFiveJobsControllerSpec.scala, test/controllers/RegisterForSelfAssessmentControllerSpec.scala, test/controllers/UsePrintAndPostControllerSpec.scala, test/forms/MoreThanFiveJobsFormProviderSpec.scala, test/utils/NavigatorSpec.scala, test/views/ClaimOnlineViewSpec.scala, test/views/MoreThanFiveJobsViewSpec.scala, test/views/RegisterForSelfAssessmentViewSpec.scala, test/views/UsePrintAndPostViewSpec.scala
Completed journey for iteration 1, with all content based around "you".
=> Iteration 1

app/controllers/ClaimingOverPayAsYouEarnThresholdController.scala, app/controllers/RegisteredForSelfAssessmentController.scala, app/controllers/actions/GetClaimantAction.scala, app/forms/ClaimingOverPayAsYouEarnThresholdFormProvider.scala, app/forms/RegisteredForSelfAssessmentFormProvider.scala, app/models/requests/DataRequest.scala, app/views/claimingOverPayAsYouEarnThreshold.scala.html, app/views/registeredForSelfAssessment.scala.html, conf/messages.en, test/controllers/ClaimingOverPayAsYouEarnThresholdControllerSpec.scala, test/controllers/ControllerSpecBase.scala, test/controllers/RegisteredForSelfAssessmentControllerSpec.scala, test/controllers/actions/GetClaimantActionSpec.scala, test/forms/ClaimingOverPayAsYouEarnThresholdFormProviderSpec.scala, test/forms/RegisteredForSelfAssessmentFormProviderSpec.scala, test/views/ClaimingOverPayAsYouEarnThresholdViewSpec.scala, test/views/RegisteredForSelfAssessmentViewSpec.scala
Added a new action to get the claimant from user answers.  The claimant can then be passed to the forms and views which need it to provide contextualised content.
=> Iteration 1 context

app/controllers/CannotClaimReliefController.scala, app/controllers/EmployerPaidBackExpensesController.scala, app/forms/EmployerPaidBackExpensesFormProvider.scala, app/identifiers/EmployerPaidBackExpensesId.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/cannotClaimRelief.scala.html, app/views/employerPaidBackExpenses.scala.html, conf/app.routes, conf/messages.en, migrations/applied_migrations/CannotClaimRelief.sh, migrations/applied_migrations/EmployerPaidBackExpenses.sh, test/controllers/CannotClaimReliefControllerSpec.scala, test/controllers/EmployerPaidBackExpensesControllerSpec.scala, test/forms/EmployerPaidBackExpensesFormProviderSpec.scala, test/utils/NavigatorSpec.scala, test/views/CannotClaimReliefViewSpec.scala, test/views/EmployerPaidBackExpensesViewSpec.scala
This iteration adds an additional question to the flow, with another endpoint if the user isn't able to claim relief.
=> Iteration 2

conf/messages.en
Updated:
- Save and continue buttons
- Another year
- Final pages
Will need you and someone else versions for the title and headings of the final pages. The "You" in both should be replaced with "They".
=> Updated content after feedback

app/controllers/RegisterForSelfAssessmentController.scala, app/controllers/UseSelfAssessmentController.scala, app/views/claimOnline.scala.html, app/views/registerForSelfAssessment.scala.html, app/views/useSelfAssessment.scala.html, conf/messages.en, test/controllers/RegisterForSelfAssessmentControllerSpec.scala, test/controllers/UseSelfAssessmentControllerSpec.scala, test/views/RegisterForSelfAssessmentViewSpec.scala, test/views/UseSelfAssessmentViewSpec.scala
I have made a couple more content changes and added content for someoneElse versions of pages.
I update the views to include the claimant variable but I am not sure if this is correct or what you will need to do to tests.
=> More content changes following feedback

app/views/cannotClaimReliefSomeYears.scala.html, app/views/notEntitled.scala.html, app/views/notEntitledSomeYears.scala.html, app/views/registerForSelfAssessment.scala.html, conf/messages.en
Updated content and views based on feedback.
I have removed guidance paragraph, although this may be added back in later. I have added the claimant variable to the button label too.
=> Updated content and views

conf/messages.en
This is to reduce length of headings and improve content in guidance.
=> Small content changes

app/assets/stylesheets/partials/_forms.scss, app/views/registerForSelfAssessment.scala.html, app/views/useSelfAssessment.scala.html
This makes it consistent with other screen where we point to guidance.
=> Changed buttons on Self Assessment pages to links

app/models/ClaimingFor.scala, conf/messages.en
Added content for new checkbox and updated the model for the checkboxes on the 'What expenses are you claiming?' page.
=> New checkbox and model

app/controllers/UseCompanyCarController.scala, app/models/UseOfOwnCar.scala, app/views/useCompanyCar.scala.html, conf/messages.en, test/controllers/UseCompanyCarControllerSpec.scala, test/forms/UseCompanyCarFormProviderSpec.scala, test/views/UseCompanyCarViewSpec.scala
If the user has previously said they use their own car, we show a
slightly different message to give context and make the question clearer.
=> Add context to UseCompanyCar

README.md
@stevenaproctor @TheNickWilson can you both have a spy at the first bash of a meaningful readme?
Cheers
Dave
=> adding content to readme

conf/messages.en
=> Updated call to action

app/models/ClaimingFor.scala, app/views/components/link_start.scala.html
Updated link component with new window option
=> EE-1019 Fix link not opening in new window when content indicates it should 

conf/messages.cy
also includes changes for 1097,1096
=> EE-1091: content changed in messages.cy

conf/messages.cy
Ticket updated to cover the blank key
=> EE-1112: updated the welsh content

project/AppDependencies.scala, project/build.properties, project/plugins.sbt, project/scaffold.sbt, test/controllers/ChangeOtherExpensesControllerSpec.scala, test/controllers/ChangeUniformsWorkClothingToolsControllerSpec.scala, test/controllers/ClaimantControllerSpec.scala, test/controllers/ClaimingForControllerSpec.scala, test/controllers/ClaimingFuelControllerSpec.scala, test/controllers/ClaimingMileageControllerSpec.scala, test/controllers/ClaimingOverPayAsYouEarnThresholdControllerSpec.scala, test/controllers/EmployerPaidBackExpensesControllerSpec.scala, test/controllers/MoreThanFiveJobsControllerSpec.scala, test/controllers/PaidTaxInRelevantYearControllerSpec.scala, test/controllers/RegisteredForSelfAssessmentControllerSpec.scala, test/controllers/UseCompanyCarControllerSpec.scala, test/controllers/UseOwnCarControllerSpec.scala, test/controllers/WillPayTaxControllerSpec.scala, test/controllers/actions/DataRequiredActionSpec.scala, test/controllers/actions/DataRetrievalActionSpec.scala, test/controllers/actions/GetClaimantActionSpec.scala, test/filters/SessionIdFilterSpec.scala, test/forms/behaviours/FieldBehaviours.scala, test/utils/NavigatorSpec.scala
*Reviewer* (Replace with your name)
=> DL-2660 - Dependency updates

build.sbt, project/AppDependencies.scala, project/plugins.sbt
Dependency updates
*Reviewer* (Replace with your name)
=> DL-3522 Updating dependencies

app/controllers/ClaimTypeController.scala, app/forms/ClaimTypeFormProvider.scala, app/identifiers/ClaimTypeId.scala, app/utils/CascadeUpsert.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/ClaimTypeView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, test/controllers/ClaimTypeControllerSpec.scala, test/forms/ClaimTypeFormProviderSpec.scala, test/views/ClaimTypeViewSpec.scala
=> DL-3979 - Created new page - Are you only claiming for WFH expenses?

app/controllers/OnlyWorkingFromHomeExpensesController.scala, app/forms/OnlyWorkingFromHomeExpensesFormProvider.scala, app/identifiers/OnlyWorkingFromHomeExpensesId.scala, app/utils/CascadeUpsert.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/OnlyWorkingFromHomeExpensesView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, test/controllers/OnlyWorkingFromHomeExpensesControllerSpec.scala, test/forms/OnlyWorkingFromHomeExpensesProviderSpec.scala, test/views/OnlyWorkingFromHomeExpensesViewSpec.scala
The first page in the new **Claiming for Working from home expenses** flow.
=> DL-3979 Created new page - Are you only claiming for WFH expenses.

README.md, app/controllers/CovidHomeWorkingController.scala, app/forms/CovidHomeWorkingFormProvider.scala, app/identifiers/CovidHomeWorkingId.scala, app/utils/CascadeUpsert.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/CovidHomeWorkingView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, test/controllers/CovidHomeWorkingControllerSpec.scala, test/forms/CovidHomeWorkingFormProviderSpec.scala, test/views/CovidHomeWorkingViewSpec.scala
=> DL-3980 - Added 'Covid Home Working'

app/config/FrontendAppConfig.scala, app/controllers/CovidHomeWorkingController.scala, app/controllers/OnlyWorkingFromHomeExpensesController.scala, app/controllers/actions/WorkingFromHomeEnabledAction.scala, conf/application.conf, test/controllers/actions/WorkingFromHomeEnabledActionSpec.scala, test/utils/MaterializerSupport.scala
Action composition created and wired up to the new working from home controllers. 
*Reviewee* (@grahampaulcook )
=> DL-4053 Feature toggle for WFH flow

app/utils/Navigator.scala, test/controllers/actions/WorkingFromHomeEnabledActionSpec.scala, test/utils/MaterializerSupport.scala, test/utils/NavigatorSpec.scala
Updated flow for the new WFH journey
*Stephen*
=> DL-3983 - Updated EmployerPaidBackExpensesController for new journey

app/config/FrontendAppConfig.scala, app/controllers/ClaimOnlineController.scala, app/viewmodels/OnwardJourney.scala, app/views/ClaimOnlineView.scala.html, conf/application.conf, test/controllers/ClaimOnlineControllerSpec.scala, test/controllers/actions/WorkingFromHomeEnabledActionSpec.scala, test/utils/MaterializerSupport.scala, test/views/ClaimOnlineViewSpec.scala
=> DL-3984 - Implemented logic for additional routing from ClaimOnline page

app/controllers/ClaimAnyOtherExpenseController.scala, app/controllers/WfhDueToCovidController.scala, app/utils/Navigator.scala, app/views/ClaimAnyOtherExpenseView.scala.html, app/views/WfhDueToCovidView.scala.html, conf/app.routes, test/controllers/ClaimAnyOtherExpenseControllerSpec.scala, test/controllers/WfhDueToCovidControllerSpec.scala, test/utils/NavigatorSpec.scala, test/views/ClaimAnyOtherExpenseViewSpec.scala, test/views/WfhDueToCovidViewSpec.scala
DL-4056
Updating routes and file names to fit prototype for WFH expenses
**/only-working-from-home-expenses** was updated to: **/claim-any-other-expense** 
**/covid-home-working** was updated to: **/wfh-due-to-covid** 
=> DL-4056 Updating routes and file names to fit prototype for WFH expenses

app/models/ClaimingFor.scala
DL-4071
Moving "Working from home" option to the top of the list for the **Select the expenses you want to claim** page
=> DL-4071 Moving WFH to top of claim-expenses radio button list

app/controllers/SessionExpiredController.scala, test/controllers/SessionExpiredControllerSpec.scala
=> DL-4052 - Changed session expiry link to go back to GOV.UK page

app/controllers/ClaimOnlineController.scala, app/identifiers/CovidHomeWorkingId.scala, app/utils/CascadeUpsert.scala, app/utils/Navigator.scala, test/controllers/ClaimOnlineControllerSpec.scala, test/controllers/WfhDueToCovidControllerSpec.scala, test/utils/NavigatorSpec.scala
=> DL-4065 - Journey Update

app/controllers/ClaimAnyOtherExpenseController.scala, app/forms/ClaimAnyOtherExpenseFormProvider.scala, app/identifiers/ClaimAnyOtherExpenseId.scala, app/models/ClaimAnyOtherExpense.scala, app/utils/CascadeUpsert.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/ClaimAnyOtherExpenseView.scala.html, conf/messages, conf/messages.cy, test/controllers/ClaimAnyOtherExpenseControllerSpec.scala, test/forms/claimAnyOtherExpenseProviderSpec.scala, test/utils/NavigatorSpec.scala, test/views/ClaimAnyOtherExpenseViewSpec.scala
- Updated /claim-any-other-expense page to match prototype (sprint 26)
- Renamed references to onlyWorkingFromHomeExpenses to claimAnyOtherExpense
*Stephen*
=> DL-4164 - update content for page 'Are you only claiming tax relief on your expenses for working from home'

app/controllers/EmployerPaidBackWfhExpensesController.scala, app/forms/EmployerPaidBackWfhExpensesFormProvider.scala, app/utils/Navigator.scala, app/views/EmployerPaidBackWfhExpensesView.scala.html, conf/app.routes, conf/application.conf, conf/messages, conf/messages.cy, test/controllers/EmployerPaidBackWfhExpensesControllerSpec.scala, test/forms/EmployerPaidBackWfhExpensesFormProviderSpec.scala, test/views/ClaimOnlineViewSpec.scala, test/views/EmployerPaidBackWfhExpensesViewSpec.scala
DL-4165
- New page: **/employer-paid-working-from-home-expenses** for the new WFH journey
=> DL-4165 - Adding employer-paid-back-wfh-expenses for new WFH journey

app/config/FrontendAppConfig.scala, app/controllers/CannotClaimWFHReliefController.scala, app/controllers/EmployerPaidBackWfhExpensesController.scala, app/forms/EmployerPaidBackWfhExpensesFormProvider.scala, app/identifiers/EmployerPaidBackWfhExpensesId.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/CannotClaimWFHReliefView.scala.html, app/views/ClaimAnyOtherExpenseView.scala.html, app/views/ClaimOnlineView.scala.html, app/views/EmployerPaidBackWfhExpensesView.scala.html, conf/app.routes, conf/application.conf, conf/messages, conf/messages.cy, test/controllers/CannotClaimWFHReliefControllerSpec.scala, test/controllers/EmployerPaidBackWfhExpensesControllerSpec.scala, test/views/CannotClaimWFHReliefViewSpec.scala, test/views/ClaimOnlineViewSpec.scala, test/views/EmployerPaidBackWfhExpensesViewSpec.scala
Latest Sprint 26 content + url changes to match the [expenses eligibility checker URLs and error messages v2](https://docs.google.com/spreadsheets/d/1mTK625XksssUuZO2BKXnHZhjBt8HYEYjAzjM2uGSgxk/edit#gid=1516965516) document
Also PR https://github.com/hmrc/employment-expenses-tax-relief-guidance-acceptance-tests/pull/13
*Reviewee* (@grahampaulcook )
=> DL-4205 Sprint 26 content and urls

app/controllers/ClaimantController.scala
**Bug fix**
Reset's the session based mongo store upon answering the 1st question in the standard flow. This ensures that any previous questions answered are removed which could result in flow deviations (based on older answers).
=> DL-4326 Reset data when answering 1st question

app/controllers/WfhDueToCovidController.scala, test/controllers/EmployerPaidBackWfhExpensesControllerSpec.scala, test/controllers/RegisteredForSelfAssessmentControllerSpec.scala, test/controllers/WfhDueToCovidControllerSpec.scala
**Bug fix**
Updated code to guard the endpoint **/claim-tax-relief-expenses/working-from-home-because-of-covid**
*Reviewee* (@grahampaulcook )
=> DL-4403 endpoint guarded

app/controllers/CannotClaimWFHReliefController.scala, app/controllers/ClaimOnlineController.scala, app/controllers/EmployerPaidBackWfhExpensesController.scala, app/forms/EmployerPaidBackWfhExpensesFormProvider.scala, app/identifiers/EmployerPaidBackExpensesId.scala, app/identifiers/EmployerPaidBackWfhExpensesId.scala, app/models/EmployerPaid.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/EmployerPaidBackWfhExpensesView.scala.html, app/views/components/input_radio_or.scala.html, conf/messages, conf/messages.cy, test/base/SpecBase.scala, test/controllers/EmployerPaidBackWfhExpensesControllerSpec.scala, test/forms/EmployerPaidBackWfhExpensesFormProviderSpec.scala, test/views/EmployerPaidBackWfhExpensesViewSpec.scala
DL-4463
New content on **/employer-pays-working-from-home-expenses** page 
Welsh is required for this page and also for:
- /only-claiming-working-from-home-tax-relief
- /working-from-home-because-of-covid
- /claim-online
- /employer-pays-working-from-home-expenses
*Reviewee* (Ahmad)
=> DL-4463 Content changes for employer paid WFH expenses page

app/config/FrontendAppConfig.scala, app/views/GovukWrapper.scala.html, conf/application.conf, project/AppDependencies.scala, test/controllers/SessionExpiredControllerSpec.scala
=> DL-5073 Integrate with tracking consent

conf/application.conf
=> DL-5221 Issue with timeouts

conf/messages, conf/messages.cy
=> DL-4993 Content change

conf/application.conf, conf/logback.xml, project/AppDependencies.scala, test/resources/test.application.conf
DL-5425
- Upgrading bootstrap-play-27 to 4.2.0 to pull in the auth-client upgrade to 5.X.X
=> DL-5425 Upgrading to bootstrap 4.2.0

app/controllers/actions/WorkingFromHomeEnabledAction.scala, build.sbt, project/AppDependencies.scala, project/build.properties, project/plugins.sbt, test/controllers/actions/WorkingFromHomeEnabledActionSpec.scala
=> DL-5741 Play 2.8 upgrade

app/controllers/ClaimingForCurrentYearController.scala, app/forms/ClaimingForCurrentYearFormProvider.scala, app/identifiers/ClaimingForCurrentYearId.scala, app/utils/Navigator.scala, app/utils/UserAnswers.scala, app/views/ClaimingForCurrentYearView.scala.html, app/views/Layout.scala.html, app/views/RegisterForSelfAssessmentView.scala.html, conf/app.routes, conf/messages, conf/messages.cy, project/AppDependencies.scala, test/utils/NavigatorSpec.scala
=> DL-5987 - changed Eligibility Checker (SA Screen)

app/config/FrontendAppConfig.scala, app/controllers/RegisteredForSelfAssessmentController.scala, app/views/RegisteredForSelfAssessmentView.scala.html, conf/application.conf, test/controllers/RegisteredForSelfAssessmentControllerSpec.scala, test/views/RegisteredForSelfAssessmentViewSpec.scala
=> DL-6088 - fix for back button

app/config/FrontendAppConfig.scala, app/controllers/EmployerPaidBackWfhExpensesController.scala, app/views/EmployerPaidBackWfhExpensesView.scala.html, conf/application.conf, test/controllers/EmployerPaidBackWfhExpensesControllerSpec.scala, test/controllers/RegisteredForSelfAssessmentControllerSpec.scala, test/views/EmployerPaidBackWfhExpensesViewSpec.scala
- [-]  I've run a dependency check to ensure all dependencies are up to date
=> DL-6094 - Back button fix

app/controllers/UseSelfAssessmentController.scala, app/views/UseSelfAssessmentView.scala.html, test/controllers/UseSelfAssessmentControllerSpec.scala, test/views/UseSelfAssessmentViewSpec.scala
- [-]  I've run a dependency check to ensure all dependencies are up to date
=> DL-6100 - use self assessment (back button)

app/controllers/DisclaimerController.scala, app/controllers/WhichYearsAreYouClaimingForController.scala, app/utils/Navigator.scala, app/views/DisclaimerView.scala.html, app/views/WhichYearsAreYouClaimingForView.scala.html, conf/messages, conf/messages.cy
=> DL-7295 Journey update

app/assets/stylesheets/employmentexpensestaxreliefguidancefrontend-app.scss, app/config/FrontendAppConfig.scala, app/controllers/DisclaimerController.scala, app/controllers/WhichYearsAreYouClaimingForController.scala, app/utils/Navigator.scala, app/views/ClaimAnyOtherExpenseView.scala.html, app/views/ClaimOnlineView.scala.html, app/views/DisclaimerView.scala.html, app/views/RegisterForSelfAssessmentView.scala.html, app/views/WhichYearsAreYouClaimingForView.scala.html, app/views/components/heading.scala.html, conf/app.routes, conf/messages, conf/messages.cy, test/controllers/DisclaimerControllerSpec.scala, test/controllers/IndexControllerSpec.scala, test/controllers/WhichYearsAreYouClaimingForControllerSpec.scala, test/utils/NavigatorSpec.scala
=> DL-6202 new tax year phase-3 changes

app/controllers/ClaimOnlineController.scala, app/views/ClaimOnlineView.scala.html, test/views/ClaimOnlineViewSpec.scala
=> DL-7414 Non-SA users directed to WFH without sessionID parameter

app/views/WillPayTaxView.scala.html, test/views/WillPayTaxViewSpec.scala
=> DL-9244 - WillPayTaxView

app/views/ClaimingOverPayAsYouEarnThresholdView.scala.html, test/views/ClaimingOverPayAsYouEarnThresholdViewSpec.scala
=> DL-9247 ClaimingOverPayAsYouEarnThresholdView

app/views/RegisterForSelfAssessmentView.scala.html, test/controllers/WfhDueToCovidStatusControllerSpec.scala, test/controllers/WhichYearsAreYouClaimingForControllerSpec.scala, test/views/RegisterForSelfAssessmentViewSpec.scala, test/views/behaviours/NewViewBehaviours.scala
=> DL-9248 RegisterForSelfAssessmentView

app/views/EmployerPaidBackExpensesView.scala.html, test/views/EmployerPaidBackExpensesViewSpec.scala
=> DL-9249 EmployerPaidBackExpensesView

app/views/CannotClaimReliefView.scala.html, test/views/CannotClaimReliefViewSpec.scala
=> DL-9250 CannotClaimReliefView

app/views/WfhDueToCovidView.scala.html, project/build.properties, test/views/WfhDueToCovidViewSpec.scala
=> DL-9252 - WfhDueToCovidView

app/models/ClaimingFor.scala, app/views/ClaimingForView.scala.html, test/views/ClaimingForViewSpec.scala, test/views/behaviours/CheckboxViewBehaviours.scala
=> DL-9251 ClaimingForView

app/views/DisclaimerView.scala.html, app/views/playComponents/submit_button.scala.html, test/views/DisclaimerViewSpec.scala
=> DL-9253 DisclaimerView

app/views/ClaimOnlineView.scala.html, app/views/playComponents/button_link.scala.html, test/views/ClaimOnlineViewSpec.scala
=> DL-9254 - ClaimOnlineView

app/views/MoreThanFiveJobsView.scala.html, test/views/MoreThanFiveJobsViewSpec.scala
=> DL-9255 MoreThanFiveJobsView

app/views/UsePrintAndPostView.scala.html, test/views/UsePrintAndPostViewSpec.scala
=> DL-9256 UsePrintAndPostView

app/views/CannotClaimReliefTooLongAgoView.scala.html, test/views/CannotClaimReliefTooLongAgoViewSpec.scala
=> DL-9258 - CannotClaimReliefTooLongAgoView

app/views/CannotClaimBuyingEquipmentView.scala.html, test/views/CannotClaimBuyingEquipmentViewSpec.scala
=> DL-9259 - CannotClaimBuyingEquipmentView

app/views/ClaimingMileageView.scala.html, test/views/ClaimingMileageViewSpec.scala
=> DL-9261 - ClaimingMileageView

app/views/UseCompanyCarView.scala.html, app/views/playComponents/input_yes_no.scala.html, test/views/UseCompanyCarViewSpec.scala
=> DL-9262 - UseCompanyCarView

app/views/Layout.scala.html, app/views/SessionExpiredView.scala.html, conf/messages, conf/messages.cy, test/controllers/SessionExpiredControllerSpec.scala, test/views/SessionExpiredViewSpec.scala
Tested session timeout dialog with:
```shell
sbt -Dsession.timeoutSeconds=130 "run 8787"
```
*Stephen*
=> DL-9266 - SessionExpiredView

app/views/ClaimAnyOtherExpenseView.scala.html, test/views/ClaimAnyOtherExpenseViewSpec.scala
=> DL-9264 - ClaimAnyOtherExpenseView

app/views/ClaimingFuelView.scala.html, test/views/ClaimingFuelViewSpec.scala
=> DL-9263 - ClaimingFuelView

app/views/UseOwnCarView.scala.html, test/views/UseOwnCarViewSpec.scala
=> DL-9260 UseOwnCarView

app/views/SaCheckDisclaimerAllYearsView.scala.html, test/views/SaCheckDisclaimerAllYearsViewSpec.scala
=> DL-9268 SaCheckDisclaimerAllYearsView

app/views/SaCheckDisclaimerCurrentYearView.scala.html, test/views/SaCheckDiclaimerCurrentYearViewSpec.scala
=> DL-9269 - SaCheckDisclaimerCurrentYearView

app/views/CannotClaimMileageCostsView.scala.html, test/views/CannotClaimMileageCostsViewSpec.scala
=> DL-9270 - CannotClaimMileageCostsView

app/views/CannotClaimMileageFuelCostsView.scala.html, test/views/CannotClaimMileageFuelCostsViewSpec.scala
=> DL-9271 - CannotClaimMileageFuelCostsView

app/views/CannotClaimReliefSomeYearsView.scala.html, test/views/CannotClaimReliefSomeYearsViewSpec.scala
=> DL-9273 CannotClaimReliefSomeYearsView

app/views/CannotClaimWFHReliefView.scala.html, test/views/CannotClaimWFHReliefViewSpec.scala
=> DL-9274 CannotClaimWFHReliefView

app/views/EmployerPaidBackWfhExpensesView.scala.html, app/views/playComponents/input_radio_or.scala.html, test/views/EmployerPaidBackWfhExpensesViewSpec.scala
=> DL-9276 EmployerPaidBackWfhExpensesView

app/views/NotEntitledView.scala.html, test/views/NotEntitledViewSpec.scala
=> DL-9277 notEntitledView.scala

app/views/WhichYearsAreYouClaimingForView.scala.html
=> DL-9479 WhichYearsAreYouClaimingForView hint text to body text

app/controllers/ClaimantController.scala, app/controllers/ClaimingForController.scala, app/utils/CascadeUpsert.scala, app/utils/Navigator.scala, test/controllers/ClaimantControllerSpec.scala, test/controllers/ClaimingForControllerSpec.scala, test/controllers/IndexControllerSpec.scala, test/utils/CascadeUpsertSpec.scala, test/utils/NavigatorSpec.scala
The new entry point has been changed to `/what-claiming-for`
*Stephen*
=> DL-9064 - Moved ClaimingFor checkboxes

conf/messages
=> DL-9536 - CannotClaimReliefTooLongAgoView

app/views/RegisteredForSelfAssessmentView.scala.html, conf/messages, conf/messages.cy
The page structure for the RegisteredForSelfAssessmentView is slightly different for the WFH journey. Added a conditional to show the additional paragraph
*Stephen*
=> DL-11845 - conditional wfh paragraph

conf/application.conf, project/AppDependencies.scala
=> DL-11976 remove csp directive

app/utils/Navigator.scala, test/controllers/WhichYearsAreYouClaimingForControllerSpec.scala
=> DL-12063 - Added /more-than-2500 page to WFH journey

app/utils/Navigator.scala, test/controllers/WhichYearsAreYouClaimingForControllerSpec.scala, test/utils/NavigatorSpec.scala
=> DL-12085 fixed issues after previous merge

app/forms/EmployerPaidBackAnyExpensesFormProvider.scala, test/forms/EmployerPaidBackAnyExpensesFormProviderSpec.scala
=> DL-12084 fix error message

conf/prod.routes, project/AppDependencies.scala, project/plugins.sbt
=> DL-12322 Depdendency updates

conf/application.conf, project/plugins.sbt
=> DL-12884 - Amended 'by post' URL

conf/messages, conf/messages.cy
=> DL-12872 modify content

project/AppDependencies.scala
=> DL-12974 update crown logo

conf/messages, conf/messages.cy
=> DL-13127 modify content

app/controllers/ClaimOnlineController.scala, app/views/ClaimOnlineView.scala.html, conf/messages, conf/messages.cy, project/plugins.sbt, test/views/ClaimOnlineViewSpec.scala
=> DL-13250 added claims on final page

app/views/ClaimOnlineView.scala.html, conf/messages, conf/messages.cy, test/views/ClaimOnlineViewSpec.scala
=> DL-13250-2 content change to heading

conf/messages.cy
=> DL-13250-3 added welsh content

app/config/FrontendAppConfig.scala, app/utils/Navigator.scala, app/views/ClaimOnlineView.scala.html, test/base/SpecBase.scala, test/controllers/IndexControllerSpec.scala, test/utils/FakeNavigator.scala, test/utils/NavigatorSpec.scala
=> DL-13453 Removing the WFH shutter redirect

app/controllers/ClaimOnlineController.scala
=> DL-13353 claim-online page bug fix

app/controllers/UsePrintAndPostController.scala, app/utils/Navigator.scala, app/views/UsePrintAndPostView.scala.html, conf/messages, conf/messages.cy, project/build.properties, project/plugins.sbt, test/utils/NavigatorSpec.scala
=> DL-10651 Improvements to vehicles journey

app/utils/Navigator.scala
=> DL-10651 Small fix for an extra journey resulting in P87

app/config/FrontendAppConfig.scala, conf/application.conf
=> DL-14395 add feature switch for online shutter journey

app/utils/Navigator.scala, test/controllers/ChangeOtherExpensesControllerSpec.scala, test/controllers/ChangeUniformsWorkClothingToolsControllerSpec.scala, test/controllers/ClaimAnyOtherExpenseControllerSpec.scala, test/controllers/ClaimantControllerSpec.scala, test/controllers/ClaimingForControllerSpec.scala, test/controllers/ClaimingFuelControllerSpec.scala, test/controllers/ClaimingMileageControllerSpec.scala, test/controllers/ClaimingOverPayAsYouEarnThresholdControllerSpec.scala, test/controllers/DisclaimerControllerSpec.scala, test/controllers/EmployerPaidBackAnyExpensesControllerSpec.scala, test/controllers/IndexControllerSpec.scala, test/controllers/MoreThanFiveJobsControllerSpec.scala, test/controllers/NotEntitledSomeYearsControllerSpec.scala, test/controllers/PaidTaxInRelevantYearControllerSpec.scala, test/controllers/RegisterForSelfAssessmentControllerSpec.scala, test/controllers/RegisteredForSelfAssessmentControllerSpec.scala, test/controllers/UseCompanyCarControllerSpec.scala, test/controllers/UseOwnCarControllerSpec.scala, test/controllers/WillNotPayTaxControllerSpec.scala, test/controllers/WillPayTaxControllerSpec.scala, test/utils/FakeNavigator.scala, test/utils/NavigatorSpec.scala
=> DL-14396: change routing based on feature flag

app/controllers/UsePrintAndPostController.scala, app/views/UsePrintAndPostDetailedView.scala.html, app/views/playComponents/h2.scala.html, app/views/playComponents/h3.scala.html, app/views/playComponents/p.scala.html, conf/messages, conf/messages.cy, test/controllers/UsePrintAndPostControllerSpec.scala, test/views/UsePrintAndPostDetailedViewSpec.scala
=> Dl 14402 - Created New PrintAndPostDetailed View Page

app/utils/Navigator.scala, test/utils/NavigatorSpec.scala
=> DL-14619 correct vehicle journey to allow more questions

app/config/FrontendAppConfig.scala, conf/application.conf
DL-14680 : Create a new feature switch (freOnlyJourney)
Added freOnlyJourney flag 
=> DL-14680: Adding freOnlyJourney flag

app/controllers/UsePrintAndPostController.scala, app/views/UsePrintAndPostDetailedView.scala.html
=> DL-14692 display correct result when only WFH is selected

conf/messages, conf/messages.cy, test/views/RegisterForSelfAssessmentViewSpec.scala
=> DL-14904:added extra text for link opening in new tab

app/models/ClaimingFor.scala, conf/messages, conf/messages.cy
DL-15018: Content update for 'Select all the expenses you want to claim' page
=> DL-15018: Content update for 'Select all the expenses you want to claim' page

project/AppDependencies.scala, project/plugins.sbt
=> DL-15075:Dependency Upgrade

app/controllers/UsePrintAndPostController.scala, app/utils/Navigator.scala, project/AppDependencies.scala, project/plugins.sbt, test/utils/NavigatorSpec.scala
DL-15192: Add extra vehicle questions in case of multi claims 
**Bug fix** (delete as appropriate)
When vehicle expenses are claimed we need these questions to be asked, even on multiple claims. The questions that are asked in single journey.
Divya Prabha Manimaran
=> DL-15192: Add extra vehicle questions in case of multi claims 

app/controllers/UsePrintAndPostController.scala
DL-15221: To show wfh content in summary page in case user comes from claim any other expense path.
Bug fix
Divya Prabha Manimaran
=> DL-15221: To show wfh content in summary page 

app/controllers/UsePrintAndPostController.scala, app/utils/Navigator.scala, test/utils/NavigatorSpec.scala
DL-15215:Push user to Iform if Airlines occupation is selected
=> DL-15215:Push user to Iform if Airlines occupation is selected

project/AppDependencies.scala
DL-15215:Updating the Bootstrap dependency
=> DL-15215:Updating the Bootstrap dependency

app/config/FrontendAppConfig.scala, conf/application.conf
DL-15683:Implementing feature switch for pega service journey
=> DL-15683:Implementing feature switch for pega service journey

app/config/FrontendAppConfig.scala, app/views/UseIformFreOnlyView.scala.html, conf/application.conf, test/views/UseIformFreOnlyViewSpec.scala
DL-15681: Adding redirection link to pega service for WFH.
New feature
Divya
=> DL-15681: Adding redirection link to pega service for WFH.

app/utils/Navigator.scala, test/utils/NavigatorSpec.scala
=> DL-15232 : Adding morethan5jobs screen at the end of journey

build.sbt, test/controllers/UsePrintAndPostControllerSpec.scala, test/generators/Generators.scala, test/utils/EnumerableSpec.scala, test/utils/MaterializerSupport.scala, test/utils/MessagesSpec.scala, test/utils/NavigatorSpec.scala, test/views/CannotClaimReliefViewSpec.scala, test/views/ClaimOnlineViewSpec.scala, test/views/ClaimingForViewSpec.scala, test/views/DisclaimerViewSpec.scala, test/views/InformCustomerClaimNowInWeeksViewSpec.scala, test/views/UsePrintAndPostFreOnlyViewSpec.scala
=> DL-16722 fixing all compilation and test compilation warnings
